# Generated by Django 3.0.8 on 2020-08-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
